baseurl = "https://javiercara.github.io/blog/"
relativeurls = true
languageCode = "en-us"
title = "The more I learn, the more I can learn"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs/"

[author]
    name="Javier Cara"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Website"
    url = "https://javiercara.github.io"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/javiercara"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/javiercara_"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "blog6.png"
    width = 50
    height = 50
    alt = "Logo"

